# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='users_liked',
            field=models.ManyToManyField(related_name='quotes_liked', to='belt_ex.User'),
        ),
    ]
