# Generated by Django 2.2.1 on 2019-05-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_ex', '0002_quotes_users_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_quote', to='belt_ex.User'),
        ),
    ]
